### ISSUE TITLE
GPU train error

### ISSUE THREAD

**Issue by danieleghisi** [phreeza/tensorflow-vrnn#1]
Hi, thanks for this great development.
I'm trying to train it on GPU and I get this error.
(if I train it on CPU everything worked fine - although super slow, of course).

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3000,1200]
	 [[Node: RNN/VartiationalRNNCell_48/LSTMCell/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/gpu:0"](RNN/VartiationalRNNCell_48/LSTMCell/MatMul, RNN/VartiationalRNNCell/LSTMCell/B/read)]]
	 [[Node: Mean_1/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_41116_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Do you why this might happen? I've cut down the mp3 base to just a few minutes, but that didn't solve it. Also, I'm using a ssh multiple-gpu machine, but I'm setting CUDA_VISIBLE_DEVICES to the only one I'm using (4GB of memory).

If you have any hint, that would be great!
d

**Comment by phreeza** [comment]
The default batch size is pretty big (3000), you may want to reduce it to something smaller?
